version: '3.8'

services:
  backend:
    build: ./Backend
    image: mohibrehman31/cosmicdailybackend:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./Backend:/app
      - /app/node_modules

  frontend:
    build: ./Frontend
    image: mohibrehman31/cosmicdailyfrontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
