version: '3.8'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-app
    environment:
      - NODE_ENV=production
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
