name: CI

'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies (Frontend)
        working-directory: ./Frontend
        run: npm ci

      - name: Build Frontend
        working-directory: ./Frontend
        run: npm run build

      - name: Test Frontend
        working-directory: ./Frontend
        run: npm test

      - name: Install dependencies (Backend)
        working-directory: ./Backend
        run: npm install

      - name: Test Backend
        working-directory: ./Backend
        run: npm test

      - name: Build Docker images
        run: docker-compose build

      - name: Run Docker containers
        run: docker-compose up -d

      - name: Wait for services to start
        run: sleep 10

      - name: Check running containers
        run: docker ps

      - name: Stop Docker containers
        run: docker-compose down